# Generated by Django 4.1.5 on 2023-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_comments_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timedata',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
